### ISSUE TITLE
Pre-alpha release

### ISSUE THREAD

**Issue by DDoSolitary** [DDoSolitary/OkcAgent#1]
This is a pre-alpha release for those who want to test.

1. Install OpenKeychain and import your authentication key in it.
2. Download [binaries.zip](https://github.com/DDoSolitary/OkcAgent/files/3400041/binaries.zip) and extract it.
3. Install `app-debug.apk`.
4. Open the `OkcAgent` app, select a crypto provider and an authentication key.
5. Copy `okc-ssh-agent` into your Termux's home directory and run `chmod +x okc-ssh-agent`
6. Run `./okc-ssh-agent <socket-path>`, replace `<socket-path>` with whatever a valid path for a Unix domain socket.
7. Open another session in Termux and run `export SSH_AUTH_SOCK=<socket-path>`.
8. Try using `ssh` in the new session.

**Comment by BlueDrink9** [comment]
To clarify: should we have a running `ssh-agent` already? If so, why not just use `$SSH_AUTH_SOCK` in the program rather than making the user specify it?

**Comment by DDoSolitary** [comment]
@BlueDrink9 No, just `okc-ssh-agent` is enough. You can consider it a drop-in replacement of `ssh-agent`.
