### ISSUE TITLE
OkcAgent endlessly waits in case of cancelled password

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#12]
![ScreenRecord-2020-07-28-04-08-23](https://user-images.githubusercontent.com/14617699/88607606-4d588d00-d088-11ea-8461-8dbeebfabcb5.gif)

**Comment by DDoSolitary** [comment]
Oops I fixed #10 for okc-gpg but forgot to test with okc-ssh-agent

**Comment by 532910** [comment]
works fine now
