### ISSUE TITLE
Not working on Android 14

### ISSUE THREAD

**Issue by JJGadgets** [DDoSolitary/OkcAgent#142]
OkcAgent seems to not start the listening daemon on Android 14 (GrapheneOS), thus all client-side commands using `okc-ssh-agent` and `okc-gpg` time out attempting to connect to the non existent daemon.

**Comment by cferr** [comment]
The issue seems to be caused by the call to `am broadcast` and the `am` wrapper script of Termux. Updating Termux utils fixes the behavior of that script and this issue as well.

**Comment by bitrate16** [comment]
> The issue seems to be caused by the call to `am broadcast` and the `am` wrapper script of Termux. Updating Termux utils fixes the behavior of that script and this issue as well.

Could you provide more details how to fix it? What is Termux utils

**Comment by bitrate16** [comment]
> OkcAgent seems to not start the listening daemon on Android 14 (GrapheneOS), thus all client-side commands using `okc-ssh-agent` and `okc-gpg` time out attempting to connect to the non existent daemon.

Check if OkcAgent app has network permission. It is required for communicating with termux okc-agent

**Comment by AeliusSaionji** [comment]
https://developer.android.com/about/versions/14/behavior-changes-14

Seems like the change needs to come from the manifest, I can't grant it via adb

**Comment by JJGadgets** [comment]
Update (solved it a few weeks back): can confirm, updating my Termux packages (inside Termux itself) solves this issue. Will close now.

**Comment by AeliusSaionji** [comment]
But it still isn't working for me, and I've only just installed it.

```
Dec 02 00:26:38.230 INFO okc-ssh-agent, protocol_version: 0, version: 0.1.2
Dec 02 00:27:56.980 INFO connected to client, id: 0
Dec 02 00:27:56.980 ERRO failed to accept the connection: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, id: 0
```

**Comment by sevmonster** [comment]
I get a timeout like also reported:
```
Dec 14 05:46:15.013 INFO connected to client, id: 2
Dec 14 05:46:15.013 INFO listening on port 35281, id: 2
Dec 14 05:46:15.123 INFO broadcast sent, waiting for app to connect, id: 2
Dec 14 05:46:25.125 ERRO failed to accept the connection: StringError("timed out waiting for app to connect"), id: 2
```
