### ISSUE TITLE
`termux-pacman` package is broken

### ISSUE THREAD

**Issue by sevmonster** [DDoSolitary/OkcAgent#143]
**Update 2**: It stopped working again, this time for another reason. Now it can't listen on the port/interface at all anymore.

**Update**: It is now working for me out of the blue, so make sure your Android and Termux userland is fully updated. As of this writing, I am running GrapheneOS build 2024032100, based on Android 14.

Similar to #142, except the reason is not due to permissions or caused by Termux package bugs. The broadcast intent seems to be sent, but either doesn't reach the app, the app isn't listening, or the response doesn't reach `okc-agent`; and during this process, the agent times out. Perhaps this is related to [broadcast changes in Android 14](https://github.com/DDoSolitary/OkcAgent/issues/142#issuecomment-1832417002).

```
Dec 14 05:46:15.013 INFO connected to client, id: 2
Dec 14 05:46:15.013 INFO listening on port 35281, id: 2
Dec 14 05:46:15.123 INFO broadcast sent, waiting for app to connect, id: 2
Dec 14 05:46:25.125 ERRO failed to accept the connection: StringError("timed out waiting for app to connect"), id: 2
```

Logcat does not show anything interesting, except perhaps this when starting the app:
```
[12-14 07:07:33.390 25358:25358 E/org.ddosolitary.okcagent]
Unable to find pattern file or unable to map it for am
```

No amount of [fiddling with permissions](https://github.com/DDoSolitary/OkcAgent/issues/129#issuecomment-1467015036) would allow it to connect, and the only thing that changed between it working and not working is my system version. Termux packages are up to date and were not changed between when it stopped working, to my recollection.

Unfortunately this app is probably dead and no one seems interested to continue maintenance. So if OkcAgent is useful to you, avoid upgrading Android or fix this bug.

**Comment by djkazic** [comment]
Have you tried the fix in https://github.com/DDoSolitary/OkcAgent/issues/142

**Comment by GammaPi** [comment]
I also encountered issues when upgrading to Android 14.
I intended to debug this just now, but after I installed Android Studio and built the app, it worked correctly.

Maybe you can try:
1. Upgrade Termux
pkg upgrade
2. Reinstall okc-agent. Revoke access from the OpenPGP keychain.
3. Re-add keys.
4. Make sure you manually allow notification permission since this app does not request it in the UI.

Then things should work?!

---------------------

It looks like JJGadgets also found this issue. He solved it by updating the Termux package.
I also observed some error logs in the "am" command before upgrading Termux. So the solution should be to upgrade termux package.

https://github.com/DDoSolitary/OkcAgent/issues/142#issuecomment-1837036480


---------------------

Please also try to kill both Termux and okc-ssh-agent after you add the key. Maybe there are some corner cases not handled well. I just did a reinstallation and killing both makes okc-ssh-agent work again. I hope this helps.

**Comment by sevmonster** [comment]
I ensured everything you are saying before submitting this issue. Namely I already linked to and commented on issue #142, so I am well aware of its contents.

**Comment by markhuge** [comment]
Okc-Agent works great for me on latest GrapheneOS release on multiple devices after a pkg update.

**Comment by sevmonster** [comment]
I re-enabled OpenKeychain and OkcAgent, and reinstalled `okc-agents` to test, and it is working for me now as well. But the app and package have not changed since when it wasn't working, so this is likely due to a fix or change in Android.

I will leave this issue open for now.

**Comment by perrin4869** [comment]
I was just having trouble with this too, the solution was indeed to add permissions for `OkcAgent` to send notifications like described here: https://github.com/DDoSolitary/OkcAgent/issues/143#issuecomment-1945316675

**Comment by sevmonster** [comment]
You're not gonna believe this, but I found out the reason `okc-ssh-agent` no longer worked for me.

For some background, and to ruin the surprise, I switched to [`pacman`](https://wiki.termux.com/wiki/Switching_package_manager) a while ago, and as such, began using the packages provided by that repository. That, among other changes, made my Termux quite personalized and far from stock. To start fresh, I reinstalled Termux and all associated apps, and what do you know, `okc-ssh-agent` worked right away with no tinkering.

Surprised but unquestioning of the gods, I reconfigured Termux to use `pacman` again, and reinstalled `okc-agents` from the `termux-pacman` repos. And now `okc-ssh-agent` stopped working again.

So, I'm not sure what changed—maybe a Go dependency or corelib—but *the `termux-pacman` build specifically* of `okc-ssh-agent` does not work at all. With the `apt` repo package, manually enabling notifications seems to be all that needs to be done to allow `okc-ssh-agent` to work.

After downloading the `deb` package and extracting the binaries from it, I found those worked, even in the new `pacman` userland. To permanently fix this issue, I copied the binaries over the `pacman`-installed ones. I hate that that fixed it but so it is.

If you're like me and want to get it working again too, do this:
```sh
pacman -S bintools wget okc-ssh-agents
# replace aarch64 with your arch
wget https://packages.termux.dev/apt/termux-main/pool/main/o/okc-agents/okc-agents_0.1.2_aarch64.deb
ar xo okc-agents_0.1.2_aarch64.deb
tar xf data.tar.xz
mv -t "$PREFIX/bin" data/data/com.termux/files/usr/bin/*
rm -rf okc-agents_0.1.2_aarch64.deb control.tar.gz data.tar.xz data debian-binary
```

Given that it seems to work for everyone on modern Android versions after enabling notifications if not already done, and my issue was something else entirely, I'll go ahead and close this.

**Comment by msva** [comment]
@sevmonster can you please reopen the issue?

It seems, it is still actual (and okc-agent having great issues with A14+)

(and it seems for now it have issues with out-of-the-box packages, even without termux-pacman)

**Comment by msva** [comment]
(btw, in my own case it says, if I run `okc-ssh-agent -Dd` it says even stranger things:

```
Mar 23 14:02:33.923 INFO connected to client, id: 3
Mar 23 14:02:33.926 ERRO failed to accept the connection: Os { code: 97, kind: Uncategorized, message: "Address family not supported by protocol" }, id: 3

```

**Comment by sevmonster** [comment]
This issue ended up being related to the `termux-pacman` repository having a broken `okc-agents` package. There is [already an issue and solution](https://github.com/DDoSolitary/OkcAgent/issues/142#issuecomment-1837036480) for the common Android 14+ problem related to notifications not being enabled.

Have you confirmed on that specific device that running a specific Android version and above causes the issue? Because that error looks like something put in place by your device vendor.

The root cause is Java trying to open `127.0.0.1` as an IPv6 address, which only happens if your JVM (ART) is compiled to prefer IPv6, without IPv4 support, has no IPv4 loopback interface, or etc.

You should open a new issue including your device information. And if possible, downgrade to earlier OS versions to triage the issue. Considering I've not seen that error before (and I've been using this project for years with various hiccups) I really doubt it is from Android and is something cause by your vendor.

Do note [Termux is implementing "basic YubiKey support"](https://github.com/termux/termux-api/issues/393#issuecomment-2704154732) soon, so if that's your use case, you may not need to bother with OkcAgent soon.

And of course, the original author is no longer around, so you shouldn't expect anyone to fix your issue regardless.
