### ISSUE TITLE
Use termux-services to start ockagent ssh daemon init system

### ISSUE THREAD

**Issue by gerardo-junior** [DDoSolitary/OkcAgent#18]
there is an init proton daemon on termux https://github.com/termux/termux-services and it would be ideal to have support on it

**Comment by DDoSolitary** [comment]
I took a look at the existing packages that support termux-services and it seems that what needs to be changed is the packaging script. So please request this change at [termux/termux-packages](https://github.com/termux/termux-packages)

**Comment by gerardo-junior** [comment]
I created a problem there, I thought it was just in the ock-agent package to put the init files. like systemd

Thanks!
