### ISSUE TITLE
Crash when selecting SSH keys

### ISSUE THREAD

**Issue by sawwashere** [DDoSolitary/OkcAgent#19]
The app appears to crash when I try to select an SSH key.
When I select my SSH key and press the select button it closes immediately and when I reopen the app it does not have the key selected.

**Comment by DDoSolitary** [comment]
Please provide some additional information:

- app version
- download source (Play Store, F-Droid, etc)
- preferably crash log

**Comment by sawwashere** [comment]
0.2.2
Google Play Store
How do I get this crash log?

**Comment by DDoSolitary** [comment]
@sawwashere 

[app-release.zip](https://github.com/DDoSolitary/OkcAgent/files/5212822/app-release.zip)

Please try this version. It is a bug that I'm thought I've already fixed in d68c8057a4c43b6bccbac292156b9b589c919274, but it seems that I didn't cover a special case when OpenKeychain reports an error.

You may need to uninstall the already installed version to install this one because it is signed with a different key.

**Comment by sawwashere** [comment]
Once I uninstalled the old version and installed your new version. I tried adding the key again and the first time I got the confirmation dialog from OpenKeychain that I wanted to allow OkcAgent to access my keys which I allowed. Then I was presented with the choose key dialog and upon making my selection and hitting select I received the following message:
"Error: Could not create description : null"

**Comment by DDoSolitary** [comment]
The error message seems to be from OpenKeychain

https://github.com/open-keychain/open-keychain/blob/7154159a3623180570cc4122fd4cb2efacf9e1c5/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/SshAuthenticationService.java#L270-L271

So I guess there's something wrong with the key.

**Comment by sawwashere** [comment]
This key is working with TermBot(ssh client app) and PasswordStore without issue.

**Comment by sawwashere** [comment]
It seems that the issue was that some of the subkeys were expired. Once I extended their life and updated the key in OpenKeychain I was able to properly select the key.
