### ISSUE TITLE
Git doesn't use the agent

### ISSUE THREAD

**Issue by sawwashere** [DDoSolitary/OkcAgent#22]
I have an ssh key added to the OKC-agent and I am able to use ssh to login to the machine/user combo directly but git fails to use the agent when trying to perform operations. I just get the "Permission denied (publickey)" message when I try.

**Comment by 532910** [comment]
I believe this issue is not related to git.

**Comment by sawwashere** [comment]
Any idea what it is related to, then?

**Comment by 532910** [comment]
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/error-permission-denied-publickey

could you describe exactly what are you doing, like:

```
user@localhost $ ssh user@remorehost
user@remotehost $
```

```
user@localhost $ git clone ssh://user@remorehost:repo
Permission denied (publickey)
```

**Comment by sawwashere** [comment]
that looks pretty much like what I'm doing, I'm just trying to use git pull instead of clone

**Comment by 532910** [comment]
Does clone work (into a new directory)?
Could you show `repo/.git/config` and .`git/config`?

**Comment by sawwashere** [comment]
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
diff.gpg.binary=true
diff.gpg.textconv=gpg2 -d --quiet --yes --compress-algo=none --no-encrypt-to --batch --use-agent
user.name=username
user.email=email
diff.submodule=diff
status.submodulesummary=1
submodule.active=.
submodule.recurse=true
alias.sdiff=!git diff && git submodule foreach 'git diff'
alias.supdate=submodule update --remote --merge
remote.origin.url=ssh://gitolite@IPv4:Port/repo
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
submodule.work.url=ssh://gitolite@IPv4:Port/subrepo
pull.rebase=false

**Comment by sawwashere** [comment]
Cloning into a new directory fails with the same message

**Comment by 532910** [comment]
```
GIT_SSH_COMMAND="ssh -vvv" git clone ssh://gitolite@IPv4:Port/subrepoe tmp
```

**Comment by 532910** [comment]
And once again, am I right that `ssh gitolite@IPv4:Port ls subrepoe` shows content?

**Comment by sawwashere** [comment]
yes, there is content in the subrepo. this exact config works for me on my desktop

**Comment by 532910** [comment]
> on my desktop

with the same key?

**Comment by sawwashere** [comment]
yep

**Comment by sawwashere** [comment]
GIT_SSH_COMMAND="ssh -vvv" git clone ssh://gitolite@IP:Port/pass tmp
Cloning into 'tmp'...
OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020
debug1: Reading configuration data /data/data/com.termux/files/usr/etc/ssh/ssh_config
debug2: resolve_canonicalize: hostname IP is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/data/data/com.termux/files/home/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/data/data/com.termux/files/home/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug2: ssh_connect_direct
debug1: Connecting to IP [IP] port Port.
debug1: Connection established.
debug1: identity file /data/data/com.termux/files/home/.ssh/id_rsa type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_rsa-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_dsa type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_dsa-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ecdsa type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ecdsa-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ecdsa_sk type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ed25519 type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ed25519-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ed25519_sk type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_xmss type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.4
debug1: match: OpenSSH_8.4 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to IP:Port as 'gitolite'
debug3: put_host_port: [IP]:Port
debug3: hostkeys_foreach: reading file "/data/data/com.termux/files/home/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /data/data/com.termux/files/home/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from [IP]:Port
debug3: order_hostkeyalgs: have matching best-preference key type ecdsa-sha2-nistp256-cert-v01@openssh.com, using HostkeyAlgorithms verbatim
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:FfhgHGuTJii/9Xs3DXSKovYrXLeX0UHo0WTGTFR847Q
debug3: put_host_port: [IP]:Port
debug3: put_host_port: [IP]:Port
debug3: hostkeys_foreach: reading file "/data/data/com.termux/files/home/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /data/data/com.termux/files/home/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from [IP]:Port
debug3: hostkeys_foreach: reading file "/data/data/com.termux/files/home/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /data/data/com.termux/files/home/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from [IP]:Port
debug1: Host '[IP]:Port' is known and matches the ECDSA host key.
debug1: Found key in /data/data/com.termux/files/home/.ssh/known_hosts:1
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_rsa
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_dsa
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_ecdsa
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_ecdsa_sk
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_ed25519
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_ed25519_sk
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_xmss
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_rsa
debug3: no such identity: /data/data/com.termux/files/home/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_dsa
debug3: no such identity: /data/data/com.termux/files/home/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_ecdsa
debug3: no such identity: /data/data/com.termux/files/home/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_ecdsa_sk
debug3: no such identity: /data/data/com.termux/files/home/.ssh/id_ecdsa_sk: No such file or directory
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_ed25519
debug3: no such identity: /data/data/com.termux/files/home/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_ed25519_sk
debug3: no such identity: /data/data/com.termux/files/home/.ssh/id_ed25519_sk: No such file or directory
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_xmss
debug3: no such identity: /data/data/com.termux/files/home/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
gitolite@IP: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by 532910** [comment]
git (github, my server on debian stable) works fine with okc/openkeychain

please show git with `GIT_SSH_COMMAND` from above

**Comment by 532910** [comment]
backtick it please!

**Comment by sawwashere** [comment]
Sorry, I'm having to post these from my phone

**Comment by 532910** [comment]
`debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory`

It just doesn't use agent. Have you exported `SSH_AUTH_SOCK`? How do you start okc?

Don't remember why, but I do:
```
ssh_socket=$HOME/../usr/tmp/okc
okc-ssh-agent $ssh_socket 2>/dev/null &|
export SSH_AUTH_SOCK=$ssh_socket
```

`&|` is `&` with detaching from terminal in zsh

**Comment by sawwashere** [comment]
From my .bashrc:
```unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK=".ssh/S.okc-agent.ssh"
fi
GPG_TTY="$(tty)"
export GPG_TTY
rm $SSH_AUTH_SOCK
okc-ssh-agent $SSH_AUTH_SOCK &```

**Comment by sawwashere** [comment]
Thank you for the help. I figured out the problem, I needed a full path in SSH_AUTH_SOCKET not a partial like I had.

**Comment by 532910** [comment]
Yep, almost wrote! It's better to prefer absolute pathes in all env.

**Comment by sawwashere** [comment]
Makes sense, foolish mistake on my part

**Comment by 532910** [comment]
Chech https://github.com/DDoSolitary/okc-agents/issues/2 BTW.

As now you spawn a new okc-ssh-agent for each tab and drop old ones.

**Comment by sawwashere** [comment]
Thanks again, I'll make that change
