### ISSUE TITLE
no keys were found on gpg encrypt

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#24]
For each encryption openkeychain asks to select a key, with the following message:
```
Please review the list of recipients!

No keys were found for these email addresses:
<ID form .password-store/.gpg-id goes here>
```
But it allows to select a key and encryption succeeds.

**Comment by DDoSolitary** [comment]
What exactly is the format of key ID do you use? Currently it only accepts the long key ID format (i.e. 16 hex characters) because it is the only thing that OpenKeychain accepts. Anything else will be treated as user IDs (normally an email address).

**Comment by 532910** [comment]
it's 40 hex characters:
```
% cat .password-store/.gpg-id | wc -c
41
```
41th is `\n`

**Comment by DDoSolitary** [comment]
Then unfortunately it is not supported by OpenKeychain. The only format of key ID that OpenKeychain provides and accepts is a 64-bit integer (which corresponds to the 16 hex characters used by gpg's long key ID). It doesn't even provide a way to retrieve the full key ID of a key, so I think there's nothing can be done on my side.

**Comment by 532910** [comment]
I've updated `.gpg-id` with 16 hex format and now it works fine. Thank you!
