### ISSUE TITLE
Can not add gpg or ssh key, App

### ISSUE THREAD

**Issue by HoboDev** [DDoSolitary/OkcAgent#27]
When I press either of the buttons nothing happens. I can't import any keys.
Trying to use okc-gpg like shown in the example "crashes" (closes?) the app and I get an error message in termux when I tap on the pinned notification.

**Comment by DDoSolitary** [comment]
More information needed:

- Your phone model and Android version
- OkcAgent app version
- Have you installed OpenKeychain?
- What exactly is the error message you get? (preferably a short video demonstrating what you did because your description is pretty unclear)

**Comment by HoboDev** [comment]
The phone is a Redmi 7s with Android 10 and MIUI 12
OkcAgent is version 0.2.3
OpenKeychain is installed.

In OkcAgent I can not select either a gpg or ssh key. Nothing happens.

In termux I used (with and without a filename after the keyname): okc-agent -es -r Testkey
Then I get two notifications:
GPG Agent Services
and
Authorization Required

When I click the latter Termux says: ERRO StringError("an error has occurred in the app"), remote_port: 42987

I hope that's more clear.

**Comment by DDoSolitary** [comment]
It seems that OkcAgent is unable to call the OpenKeychain app. Please try enabling the "autostart" permission for OpenKeychain, and if it doesn't work, try disabling MIUI optimization in developer settings.

**Comment by HoboDev** [comment]
Thanks doing both did the trick.
