### ISSUE TITLE
Getting popups saying OpenKeyChain is not installed yet it is - OKCAgent works fine otherwise

### ISSUE THREAD

**Issue by Tycho-S** [DDoSolitary/OkcAgent#28]
So, as of lately I've been getting very frequent popups saying that OKCAgent can't connect to OpenKeyChain and asking me to install it: 

![OKC](https://user-images.githubusercontent.com/11061880/103171352-e6641d80-484b-11eb-9cfd-b0037bb9293b.jpeg)

Yet, OpenKeyChain is installed and configured just fine. Authenticating in Termux with SSH works normally with the Yubikey I chose in OKCAgent.

The popups keep happening when I'm in other apps than OKC, OKCAgent or Termux. Especially when I switch to other apps like Firefox. I'm wondering if this has to do with OKC being killed in the background and OKCAgent losing access to it as a result? My phone is an S8 so quite low on RAM these days.

Perhaps even a toggle to stop this from appearing would work, at the moment it's quite annoying constantly popping up :) I didn't see a settings menu in OKCAgent.

PS I use the version from the play store, 0.2.3. It's really really great to finally be able to use my SSH keys in Termux, and to be able to use them with SSH forwarding as well (which never worked in TermBot).

**Comment by DDoSolitary** [comment]
It is pretty strange because in version 0.2.3, the only possibility of triggering such an error dialog is that the app fails to connect to OpenKeychain when you're selecting an SSH/GPG key in the app. But you said that you're not using the app when the dialog pops up.
