### ISSUE TITLE
Exception using okc-ssh-agent with ed25519 authentication subkey

### ISSUE THREAD

**Issue by mkinitbtcio** [DDoSolitary/OkcAgent#29]
Just wanted to start with saying thanks for building this, it's really great I can use my hardware keys with my phone.

## Setup

I'm having an issue using `okc-ssh-agent` with an ed25519 key with `Termux`. The key is an authentication only key stored as a subkey on a YubiKey. I have tested `okc-ssh-agent` with an RSA-4096 ssh authentication key and had no issues, but I wanted to rotate the key for an ed25519 as I prefer them for usability reasons for ssh keys.

## Error Message

In `Termux` when I try to ssh I get the following error:
```
$ ssh user@host_ip
sign_and_send_pubkey: signing failed for ED25519 "Full Name <name@domain.com> (0xdeadbeef)" from agent: agent refused operation
```

At the same time there is an Exception shown in the notification bar under `OkcAgent`:
```
Exception in executeApi call : Attempt to invoke virtual method 'long org.bouncycastle.openpgp.PGPPrivateKey.getKeyID()' on a null object reference
```

## Steps to reproduce

1. Setup YubiKey in OpenKeychain with ED25519 Authentication Subkey.
2. Add ED25519 key in OkcAgent.
3. Install Termux + okc-agents package
4. Start `okc-ssh-agent` and export `SSH_AUTH_SOCKET`
5. SSH into host
6. Error thrown

**Comment by DDoSolitary** [comment]
It seems to be a known issue of OpenKeychain: open-keychain/open-keychain#2538

**Comment by ds6** [comment]
@mkinitbtcio
@msfjarvis [cut an OpenKeychain APK](https://dl.msfjarvis.dev/share/OpenKeychain-google-release.apk) that should fix the issue.
Source: [android-password-store/open-keychain](https://github.com/android-password-store/open-keychain)
See also: https://github.com/android-password-store/Android-Password-Store/issues/1272#issuecomment-782803439
