### ISSUE TITLE
How to use okc-ssh-agent?

### ISSUE THREAD

**Issue by rEnr3n** [DDoSolitary/OkcAgent#30]
I'm having trouble understanding the docs. I have installed openkeychain, termux, and okcagent (app and termux package). I have selected my gpg and ssh key inside the okcagent app.

This command gives an error "No such file or directory".
`okc-ssh-agent $PREFIX/tmp/socket &`

If I just run `okc-ssh-agent` and `ssh user@host`, it asks me for password instead.

**Comment by DDoSolitary** [comment]
The documentation in README is a bit outdated. Latest version of okc-ssh-agent has a similar CLI as ssh-agent, so you can use `eval $(okc-ssh-agent)` to get it running.

**Comment by rEnr3n** [comment]
Thanks. That works.

But why does `eval $(okc-ssh-agent)` work but not `okc-ssh-agent`?

**Comment by DDoSolitary** [comment]
The `SSH_AUTH_SOCK` environment variable has to be set to make SSH clients work with the agent. `okc-ssh-agent` outputs necessary shell commands to set the variable, and `eval` executes these commands.
