### ISSUE TITLE
Error converting public key to SSH format: Unknown key algorithm

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#46]
I looks like new OpenKeychain breaks OkcAgent:

![image](https://user-images.githubusercontent.com/14617699/109665846-a6892180-7b7f-11eb-9613-c430bb7c9e17.png)

**Comment by DDoSolitary** [comment]
It seems that OpenKeychain's developer said it's fixed on their side. Could you please check it out?

**Comment by 532910** [comment]
Sure, as soon as it becomes available on F-Droid.
