### ISSUE TITLE
Okc agent hanging

### ISSUE THREAD

**Issue by holderl5** [DDoSolitary/OkcAgent#48]
Previously, this was working.  Now when I run it it hangs and never returns.  What can I do to give you troubleshooting information?

`okc-ssh-agent $PREFIX/tmp/socket`

This the command I am currently running.  

I installed the paid app.  I went to check just now if it has any updates and Google play was asking me to enable the app.  Enabling, opening, and then running the command did not change anything.

**Comment by DDoSolitary** [comment]
Please provide some additional information:

- Version of the OkcAgent app
- Version of the command line tools (`dpkg -l okc-agents` if you installed from Termux's package repository)
- Android version

**Comment by holderl5** [comment]
* if I go to the Play Store page, I see Whats new: Last updated 11/21/2020.  Releases/tag/v0.2.3
 * 0.1.2 according to dpkg
 * Android 11 on a samsung galaxy note 20

**Comment by DDoSolitary** [comment]
> 0.1.2 according to dpkg

The command line interface of okc-ssh-agent has changed in v0.1.2 and behaves more like the traditional ssh-agent from OpenSSH. You can run `okc-ssh-agent -h` for its usage.

However, it's pretty surprising to me that the agent hangs when given wrong arguments. On my device, it prints an error message as expected:
![image](https://user-images.githubusercontent.com/25856103/115152085-46542d80-a0a2-11eb-9a7d-db981daedb8e.png)

**Comment by holderl5** [comment]
Thanks for the reply.  I will check and let you know.  This is my second in line backup plan in case I have to do support while on vacation, so I haven’t had to use it in a while.

Thank you,
John

**Comment by holderl5** [comment]
This is definitely odd.   It no longers hangs, and all versions are the same as reported above.  I get the same thing you have in the screenshot above now.   

I can guarantee you that I rebooted several times both before and after reporting the problem originally.  Before, because I wanted to make sure whatever openkeychain updates were through the system, and after just because I normally reboot every few days.

Thanks for your help.  I will report if anything else odd happens.
