### ISSUE TITLE
Don't echo agent pid

### ISSUE THREAD

**Issue by baitmooth** [DDoSolitary/OkcAgent#65]
I start the okc-ssh-agent with a script similar to [Starting okc-ssh-agent automatically](https://github.com/DDoSolitary/OkcAgent#starting-okc-ssh-agent-automatically). When the file in tmp gets sourced it writes a line about the agent PID. I don't need this line and find it slightly annoying.
Is there a way to get rid of it? eg a switch for the commandline...

Thanks

**Comment by DDoSolitary** [comment]
No, it's not supported by OpenSSH's ssh-agent either. However, you can simply append `2> /dev/null` to the command

**Comment by baitmooth** [comment]
The content of $PREFIX/tmp/okc-ssh-agent.env is:
`SSH_AUTH_SOCK="/data/data/com.termux/files/usr/tmp/okc-ssh-cOhzKmehJB/agent.25033"; export SSH_AUTH_SOCK;
SSH_AGENT_PID=25034; export SSH_AGENT_PID;
echo Agent pid 25034;`
So when sourcing it the last line is the `echo` command which I wanted to suppress. Redirect stderr was not the solution, but `>/dev/null` worked.

Thanks for the hint.
