### ISSUE TITLE
What GCM is used for?

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#7]
This is Lineage + microG:
![image](https://user-images.githubusercontent.com/14617699/85116921-b564b980-b226-11ea-9523-973b36cb127d.png)

**Comment by DDoSolitary** [comment]
I'm not very sure why it uses GCM because I didn't use it explicitly in my code. Probably it's used by the Firebase Performance and Crashlytics tools that I added to collect crash information.

**Comment by 532910** [comment]
Looks so, F-Droid version has no GCM registration.
