### ISSUE TITLE
unable to use okc-gpg, only okc-ssh-agent works?

### ISSUE THREAD

**Issue by Jan69** [DDoSolitary/OkcAgent#83]
this was an issue for me a while back on android 6 too, and on android 8, now on android 11, always  same no matter if it's the stable, or dev versions (of either the app or the CLI):
```
~/tmp $ ./okc-gpg --help
Nov 27 03:42:24.111 ERRO java.lang.Exception: No supported action is found, remote_port: 40942
Nov 27 03:42:24.112 ERRO StringError("an error has occurred in the app"), remote_port: 40942
```
the remote_port changes, of course...  
meanwhile okc-ssh-agent works fine...

**Comment by DDoSolitary** [comment]
Unfortunately okc-gpg doesn't support --help for now. Supported arguments can be found in https://github.com/DDoSolitary/OkcAgent/blob/master/app/src/main/java/org/ddosolitary/okcagent/gpg/GpgArguments.kt

**Comment by Jan69** [comment]
ah, it needs `--option` not just `option` and also doesn't act as an agent and doesn't have helptext...alright...

**Comment by Jan69** [comment]
is there a method to use a specific subkey though?

**Comment by DDoSolitary** [comment]
No, because OpenKeychain doesn't support that.
