### ISSUE TITLE
bintray.com -> github

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#9]
What is the reason to use bintray for binaries while they can be uploaded directly into github releases?

**Comment by DDoSolitary** [comment]
The binaries are automatically built by GitHub Actions on every push. It's a bad idea to create a GitHub release for every commit.

**Comment by 532910** [comment]
Hm, agree.
But releases (not dev builds) should be uploaded on github.

**Comment by DDoSolitary** [comment]
You're right. I'll definitely use GitHub Releases to publish binaries for the next release. Currently I plan to make a v0.2.0 release after fixing #6.
